import { CanvasElement } from "./types";

export const CANVAS_ELEMENTS = [
  {
    id: "mood:sketch",
    x: 440,
    y: 200,
    width: 340,
    height: 400,
    src: "/assets/images/mood/sketch.webp",
    alt: "Sketch",
  },
  {
    id: "mood:polaroids-bill-atkinson",
    x: 400,
    y: 580,
    width: 280,
    height: 220,
    src: "/assets/images/mood/bill-atkinson-lisa-polaroids.webp",
    alt: "Polaroids by Bill Atkinson",
  },
  {
    id: "mood:flow-diagram",
    x: 720,
    y: 218,
    width: 380,
    height: 260,
    src: "/assets/images/mood/flow-diagram.webp",
    alt: "Flow diagram",
  },
  {
    id: "mood:caravaggio",
    x: 800,
    y: 500,
    width: 400,
    height: 400,
    src: "/assets/images/mood/caravaggio.webp",
    alt: "Caravaggio",
  },
  {
    id: "mood:nasa-spacecraft-markings",
    x: 1130,
    y: 180,
    width: 600,
    height: 400,
    src: "/assets/images/mood/nasa-spacecraft-markings.webp",
    alt: "NASA Spacecraft Markings",
  },
  {
    id: "mood:neue-haas-grotesk-specimen",
    x: 1640,
    y: 180,
    width: 320,
    height: 430,
    src: "/assets/images/mood/neue-haas-grotesk-specimen.webp",
    alt: "Neue Haas Grotesk alphabet specimen poster",
  },
  {
    id: "mood:neue-haas-grotesk-refined-spacing",
    x: 1580,
    y: 650,
    width: 320,
    height: 420,
    src: "/assets/images/mood/neue-haas-grotesk-refined-spacing.webp",
    alt: "Neue Haas Grotesk comparisons highlighting refined spacing",
  },
  {
    id: "mood:neue-haas-grotesk-digital-era",
    x: 1900,
    y: 200,
    width: 360,
    height: 360,
    src: "/assets/images/mood/neue-haas-grotesk-digital-era.webp",
    alt: "Essay on the digital era of Neue Helvetica with warm quote",
  },
  {
    id: "mood:neue-haas-grotesk-history",
    x: 1890,
    y: 640,
    width: 340,
    height: 420,
    src: "/assets/images/mood/neue-haas-grotesk-history.webp",
    alt: "History of Neue Haas Grotesk with Helvetica brochure",
  },
  {
    id: "mood:apple-think-different",
    x: 80,
    y: 300,
    width: 312,
    height: 400,
    src: "/assets/images/mood/apple-think-different.webp",
    alt: "Apple Think Different - Yum campaign",
  },
  {
    id: "mood:out-of-the-box",
    x: 80,
    y: 740,
    width: 390,
    height: 260,
    src: "/assets/images/mood/out-of-the-box.webp",
    alt: "Out of the box, by Special Projects",
  },
] satisfies CanvasElement[];
