export interface CanvasImage {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
  src: string;
  alt: string;
}

export const CANVAS_IMAGES: CanvasImage[] = [
  {
    id: "sketch",
    x: 440,
    y: 200,
    width: 340,
    height: 400,
    src: "/assets/images/mood/sketch.webp",
    alt: "Sketch",
  },
  {
    id: "polaroids-bill-atkinson",
    x: 400,
    y: 580,
    width: 280,
    height: 220,
    src: "/assets/images/mood/bill-atkinson-lisa-polaroids.webp",
    alt: "Polaroids by Bill Atkinson",
  },
  {
    id: "flow-diagram",
    x: 720,
    y: 218,
    width: 380,
    height: 260,
    src: "/assets/images/mood/flow-diagram.webp",
    alt: "Flow diagram",
  },
  {
    id: "caravaggio",
    x: 800,
    y: 500,
    width: 400,
    height: 400,
    src: "/assets/images/mood/caravaggio.webp",
    alt: "Caravaggio",
  },
  {
    id: "nasa-spacecraft-markings",
    x: 1130,
    y: 180,
    width: 600,
    height: 400,
    src: "/assets/images/mood/nasa-spacecraft-markings.webp",
    alt: "NASA Spacecraft Markings",
  },
  {
    id: "earthrise-apollo-8-nasa-1968",
    x: 1230,
    y: 620,
    width: 280,
    height: 293,
    src: "/assets/images/mood/earthrise-apollo-8-nasa-1968.avif",
    alt: "Earthrise photograph from Apollo 8 by NASA, 1968",
  },
  {
    id: "neue-haas-grotesk-specimen",
    x: 1640,
    y: 180,
    width: 320,
    height: 430,
    src: "/assets/images/mood/neue-haas-grotesk-specimen.webp",
    alt: "Neue Haas Grotesk alphabet specimen poster",
  },
  {
    id: "neue-haas-grotesk-refined-spacing",
    x: 1580,
    y: 650,
    width: 320,
    height: 420,
    src: "/assets/images/mood/neue-haas-grotesk-refined-spacing.webp",
    alt: "Neue Haas Grotesk comparisons highlighting refined spacing",
  },
  {
    id: "neue-haas-grotesk-digital-era",
    x: 1900,
    y: 200,
    width: 360,
    height: 360,
    src: "/assets/images/mood/neue-haas-grotesk-digital-era.webp",
    alt: "Essay on the digital era of Neue Helvetica with warm quote",
  },
  {
    id: "neue-haas-grotesk-history",
    x: 1890,
    y: 640,
    width: 340,
    height: 420,
    src: "/assets/images/mood/neue-haas-grotesk-history.webp",
    alt: "History of Neue Haas Grotesk with Helvetica brochure",
  },
  {
    id: "apple-think-different",
    x: 80,
    y: 300,
    width: 312,
    height: 400,
    src: "/assets/images/mood/apple-think-different.webp",
    alt: "Apple Think Different - Yum campaign",
  },
  {
    id: "out-of-the-box",
    x: 80,
    y: 740,
    width: 390,
    height: 260,
    src: "/assets/images/mood/out-of-the-box.webp",
    alt: "Out of the box, by Special Projects",
  },
  {
    id: "geist-pixel",
    x: 2280,
    y: 700,
    width: 320,
    height: 311,
    src: "/assets/images/mood/geist-pixel.webp",
    alt: "Geist Pixel typeface",
  },
  {
    id: "loewe-mongogram",
    x: 1320,
    y: -310,
    width: 300,
    height: 453,
    src: "/assets/images/mood/loewe-mongogram.webp",
    alt: "Loewe anagram and logo on yellow leather",
  },
  {
    id: "windows-2000-professional",
    x: 2040,
    y: -150,
    width: 400,
    height: 300,
    src: "/assets/images/mood/windows-2000-professional.webp",
    alt: "Microsoft Windows 2000 Professional startup screen",
  },
  {
    id: "swiss-passport-2021-crosses-spread",
    x: 740,
    y: -220,
    width: 360,
    height: 360,
    src: "/assets/images/mood/swiss-passport-2021-crosses-spread.webp",
    alt: "Swiss passport spread with white crosses",
  },
  {
    id: "swiss-passport-arctic-map-spread",
    x: 320,
    y: -220,
    width: 360,
    height: 360,
    src: "/assets/images/mood/swiss-passport-arctic-map-spread.webp",
    alt: "Swiss passport arctic map spread",
  },
];
